CityOptics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('products/', include('products.urls')),
    path('appointments/', include('appointments.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/appointments/', include('appointments.api_urls')),
    path('api/products/', include('products.api_urls')),
    path('api/accounts/', include('accounts.api_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'CityOptics Administration'
admin.site.index_title = 'Overview'

accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.CustomerLoginView.as_view(), name='login'),
    path('logout/', views.CustomerLogoutView.as_view(), name='logout'),
    path('profile/<slug:slug>', views.profile, name='profile'),
    path('testimony/', views.testify, name='testimony'),
    path('edit-testimony/<slug:slug>/', views.edit_testimony, name='edit_testimony'),
]

htmx_urlpatterns = [
    path('hx_username', views.hx_username, name='hx_username')
]

urlpatterns += htmx_urlpatterns

accounts/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)
    email = models.CharField(max_length=55, unique=True)
    phone = models.CharField(max_length=99, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    discount_used = models.BooleanField(default=False)
    code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return self.user.username

    def __repr__(self):
        return self.user.username

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save()
        value = f"{self.user.first_name} {self.user.last_name} {self.user.username}"
        if self.slug is None:
            self.slug = slugify(value)
            self.save()


class Coupon(models.Model):
    code = models.CharField(max_length=36)
    used_on = models.DateTimeField(auto_now_add=True)
    user = models.OneToOneField(Customer, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.code

    objects = models.Manager()


class Testimony(models.Model):
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE)
    comment = models.TextField(max_length=555)
    date_created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)
    image = models.ImageField(default='cat.jpg', upload_to='feedback_pics')

    def __str__(self):
        return self.customer.user.username

    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'Testimonies'

appointments/models.py
from django.db import models

from accounts.models import Customer


class Appointment(models.Model):

    HOURS = [
        ('9H', '9H - 10H'),
        ('10H', '10H - 11H'),
        ('11H', '11H - 12H'),
        ('12H', '12H - 13H'),
        ('13H', '13H - 14H'),
        ('14H', '14H - 15H'),
        ('15H', '15H - 16H'),
        ('16H', '16H - 17H')
    ]

    name = models.CharField(max_length=150)
    phone = models.CharField(max_length=33)
    email = models.EmailField(blank=True, null=True)
    hour = models.CharField(max_length=33, choices=HOURS)
    message = models.TextField(blank=True, null=True)
    is_confirmed = models.BooleanField(default=False)
    date = models.DateField()
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.name} requests for: {self.date}, {self.hour}'

    objects = models.Manager()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Custom APP imports
from .models import Testimony


class CustomerCreationForm(UserCreationForm):
    first_name = forms.TextInput()
    last_name = forms.TextInput()
    field_order = ["username", "first_name", "last_name", "email", "password1", "password2"]

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]

        labels = {
            'first_name': '',
            'last_name': '',
            'username': '',
            'email': '',
            'phone': '',
        }
        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control form-control-lg mt-3 mb-3', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control form-control-lg mt-3 mb-3', 'placeholder': 'Last Name'}),
            'username': forms.TextInput(
                attrs={'class': 'form-control mt-3 mb-3', 'placeholder': 'Username',
                       'hx-get': '/accounts/hx_username', 'hx-target': '#used-username', 'hx-swap': 'innerHtml',
                       'hx-trigger': 'keyup delay:300ms'}),
            'email': forms.TextInput(
                attrs={'class': 'form-control form-control-lg mt-3 mb-3', 'placeholder': 'Email Address'}),
        }


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class TestimonyForm(forms.ModelForm):
    agree = forms.BooleanField(
                        required=True,
                        label='CityOptics can post my comment and username on Home Page and make it public'
                               )

    class Meta:
        model = Testimony
        fields = ('comment', 'image', 'agree')

        labels = {
            'comment': 'My Testimony',
            'image': 'Choose an Optional Image'
        }
        widgets = {
            'comment': forms.Textarea(
                attrs={'class': 'form-control form-control-lg mt-3 mb-3', 'placeholder': 'Comment here...'})}

accounts/views.py
from django.db.utils import IntegrityError
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse
from django.core.exceptions import ObjectDoesNotExist

# Custom APP imports
from .forms import CustomerCreationForm, CustomerUpdateForm, TestimonyForm
from .models import Customer, Coupon
from .serializers import CustomerSerializer, CouponSerializer, RegistrationSerializer

# Third party imports
from rest_framework.views import APIView, Response
from rest_framework.permissions import IsAdminUser, AllowAny
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.authtoken.models import Token


def register(request):
    if request.user.is_authenticated:
        messages.info(request, f'You are already registered and signed In as {request.user.customer}')
        return redirect('profile', slug=request.user.customer.slug)
    if request.method != 'POST':
        form = CustomerCreationForm()
        context = {'form': form}
        return render(request, 'accounts/register.html', context)
    form = CustomerCreationForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request, 'You successfully Registered. Discount code is sent to your email. Log IN')
        return redirect('login')
    else:
        form = CustomerCreationForm(request.POST)
        context = {'form': form}
        return render(request, 'accounts/register.html', context)


class CustomerLoginView(LoginView):
    template_name = 'accounts/login.html'
    form_class = AuthenticationForm
    redirect_authenticated_user = True


class CustomerLogoutView(LogoutView):
    template_name = 'accounts/logout.html'


@login_required
def profile(request, slug):
    if request.method == "POST":
        form = CustomerUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile Updated')
            context = {
                'object': 'Profile',
                'form': CustomerUpdateForm(instance=request.user),
                'customer': request.user.customer
            }
            return render(request, 'accounts/profile.html', context)
        else:
            return redirect('city-optics')

    else:
        try:
            customer = Customer.objects.get(slug=slug)
            form = CustomerUpdateForm(instance=request.user)
            context = {
                'customer': customer,
                'object': 'Profile',
                'form': form
            }
            return render(request, 'accounts/profile.html', context)
        except ObjectDoesNotExist:
            raise Http404


@login_required
def testify(request):
    if request.method == "POST":
        form = TestimonyForm(request.POST)
        if form.is_valid() and form.cleaned_data.get('agree'):
            testimony = form.save(commit=False)
            try:
                testimony.customer = request.user.customer
                testimony.save()
            except ObjectDoesNotExist:
                messages.warning(request, 'You are not registered Customer')
                return redirect('city-optics')
            except IntegrityError:
                messages.info(request, 'You have already posted your testimony')
                return redirect('profile', slug=request.user.customer.slug)
            messages.success(request, 'Your testimony has been sent to our Admins for verification.')
            return redirect('profile', slug=request.user.customer.slug)
        else:
            return render(request, 'accounts/testimony.html', {'form': form})

    else:
        form = TestimonyForm()
        context = {'form': form}
        return render(request, 'accounts/testimony.html', context)


def edit_testimony(request, slug):
    customer = Customer.objects.get(slug=slug)
    if request.user != customer.user:
        raise Http404
    try:
        customer = Customer.objects.get(slug=slug)
        if request.method == 'POST':
            form = TestimonyForm(request.POST, request.FILES, instance=customer.testimony)
            if form.is_valid():
                testimony = form.save(commit=False)
                testimony.approved = False
                testimony.save()
                messages.success(request, 'Updated!')
                return redirect('profile', slug=request.user.customer.slug)

        else:
            form = TestimonyForm(instance=customer.testimony)
            context = {'form': form}
            return render(request, 'accounts/edit_testimony.html', context)
    except ObjectDoesNotExist:
        messages.info(request, 'Post your testimony.')
        customer = Customer.objects.get(slug=slug)
        form = CustomerUpdateForm(instance=request.user)
        context = {
            'customer': customer,
            'object': 'Profile',
            'form': form
        }
        return render(request, 'accounts/profile.html', context)


# API views

class CustomerAPIView(APIView):
    permission_classes = [IsAdminUser]

    @staticmethod
    def get_object():
        try:
            return Customer.objects.all()
        except ObjectDoesNotExist:
            raise status.HTTP_404_NOT_FOUND

    def get(self, request):
        queryset = self.get_object()
        serializer = CustomerSerializer(queryset, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CouponAPIView(APIView):
    permission_classes = [IsAdminUser]

    @staticmethod
    def get_object():
        try:
            return Coupon.objects.all()
        except ObjectDoesNotExist:
            raise status.HTTP_404_NOT_FOUND

    def get(self, request):
        queryset = self.get_object()
        serializer = CouponSerializer(queryset, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    @staticmethod
    def post(request):
        serializer = CouponSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_404_NOT_FOUND)


@api_view(['POST'])
@permission_classes((AllowAny, ))
def registration_view(request):
    if request.method == 'POST':
        serializer = RegistrationSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            data['response'] = 'Successfully registered new user.'
            data['email'] = user.email
            data['username'] = user.username
            token = Token.objects.get(user=user).key
            data['token'] = token
        else:
            data = serializer.errors
        return Response(data)


# HtmX views
# View for giving suggestions on register page
def hx_username(request):
    username = request.GET.get('username')
    if username:
        if User.objects.filter(username=username).exists():
            return HttpResponse(f'<p style="color:red; font-size:17px;">Username: {username} is not available!</p>')
        return HttpResponse(f'<p style="color:green;">Username: {username} is available.</p>')
    return HttpResponse('Hints')

accounts/templates/accounts/account_created.html
Hello {{name}},

You successfully registered on CityOptics on {{ date }} and earned your 5% registration discount.
Please use code inside the brackets ({{code}}) when ordering your Product.
Enjoy in surfing through our offers.

This is an automated mail, please do not reply.

accounts/templates/accounts/edit_testimony.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Testimony{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<br><br><hr style="width:70%;">
<div class="container tm-container-contact">
    <div class="row">
        <div class="col">
              <center><h2 class="tm-section-title mb-4 mt-4">Edit your testimony</h2></center>
        </div>
    </div><br>
    <div class="row">
        <div class="text-center col-7 mr-auto">
            <h4 class="mb-4">
                Adjust the field content and submit
            </h4>
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form|crispy }}
             <input type="submit" class="btn tm-btn-submit" value="Submit">
            </form>
        </div>

        <div class="col-3 ml-auto">
            <h4 class="mb-4">We care about your impressions!</h4>
            <p>By editing your testimony, it will be sent to our Admins again and after a verification, again posted
                on our web site`s Home Page.</p>
            <small>Thank you for your effort.</small>
        </div>
        <div class="col-sm-12 col-md-6">

        </div>
    </div>
</div>
<hr style="width:70%;">

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<br><br><br>
<div class="container tm-container-contact">
    <div class="row">
        <div class="text-center col-12">
            <h2 class="tm-section-title mb-2">Log IN</h2>
            <p class="mb-4">
                Fill out the form and login
            </p>
        </div>

        <div class="col-sm-12 col-md-6">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form|crispy }}
             <input type="submit" class="btn tm-btn-submit" value="Login">
            </form>
            <hr>
            <small>You haven`t registered? Follow this <a href="{% url 'register' %}">Link</a></small>
        </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Logout{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<br><br><br>
<div class="container tm-container-contact">
    <div class="row">
        <div class="text-center col-12">
            <h2 class="tm-section-title mb-2">Log out</h2>
            <p class="mb-4">
               You are logged out?
            </p>
            <p><a href="{% url 'login' %}">Log IN </a>again</p>
            <p><a href="{% url 'city-optics' %}">Back to Main Page</a></p>
        </div>

<!--        <div class="col-sm-12 col-md-6">-->
<!--            <form method="POST" enctype='multipart/form-data'>-->
<!--                {% csrf_token %}-->
<!--                {{ form|crispy }}-->
<!--             <input type="submit" class="btn tm-btn-submit" value="Login">-->
<!--            </form>-->
<!--        </div>-->
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Profile{% endblock title %}

{% block content %}

{% include 'navbar.html' %}

<div style="margin:25px;">
    <br>
    <hr style="width: 70%;">
</div>

<div class="container">
    <div class="row">
        <div class="col-7">
            <h1>Welcome {{customer.user.username|upper}}</h1>
            <small>Thanks for registering.</small>
        </div>

        {% if customer.user.id == request.user.id %}
        <div class="col-5">
            <div class="container">
                <h5>Your coupon code is: </h5><p>{{customer.code}}</p>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-7">
            <small>Date joined: {{customer.created_on}}</small>
        </div>
        <div class="col-5">
            {% if customer.discount_used %}
            <small>You have used your coupon code</small>
            {% else %}
            <small>You still have not used your coupon code. Check out our </small><a href="{% url 'all_products' %}">Products</a>
            {% endif %}
        </div>
    </div>
</div>
<hr style="width: 70%;"/><br/><br/>
{% if customer.user.id == request.user.id %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <p>Update your profile:</p>
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn tm-btn-submit" value="Update" style="background:#2e5078;">
            </form>
        </div>
        <div class="col-5 ml-auto">
            <center><p>My Orders: </p></center>
            <div class="list-group mb-5">
                <a href="{% url 'order' %}" class="list-group-item list-group-item-action active"
                   aria-current="true" style="background:#2e5078;">
                    Go to Orders
                </a>
                {% for order in customer.orders.all %}
                <a href="{% url 'product_details' order.product.pk %}" type="button" class="list-group-item list-group-item-action">{{ order.product.name }}
                    <cite {% if order.discount_approved %}style="text-decoration:line-through;" {% endif %}>${{order.product.price}}</cite>
                    | </a><a type="button" class="list-group-item list-group-item-action">
                {% if order.is_shipped %}It is Shipped | {% endif %}{% if order.discount_approved %}
                You applied coupon on this Order, new price ${{ order.new_price|floatformat:2 }}{% else %}You had no
                discount{% endif %}</a>
                <hr>
                {% endfor %}
            </div>
            <center><p>My Appointments: </p></center>
            <div class="list-group mb-5">
                <a href="{% url 'appointment' %}" class="list-group-item list-group-item-action active"
                   aria-current="true" style="background:#2e5078;">
                    Go to Appointments
                </a>
                {% for appointment in customer.appointment_set.all %}
                <button type="button" class="list-group-item list-group-item-action">Requested appointment on:
                    {{ appointment.date }}, {{appointment.hour}} | {% if appointment.is_confirmed %}Your Appointment is
                    confirmed on
                    {{ appointment.date}}, {{appointment.hour}}{% else %}Your appointment is not confirmed yet.
                    {% endif %}
                </button>
                {% endfor %}
            </div>
             <center><p>My Feedback: </p></center>
            <div class="list-group mb-5">
                {% if customer.testimony %}
                <a href="{% url 'edit_testimony' customer.slug %}" class="list-group-item list-group-item-action active"
                   aria-current="true" style="background:#2e5078;">
                    Edit my Feedback
                </a>
                {% else %}
                <a href="{% url 'testimony' %}" class="list-group-item list-group-item-action active"
                   aria-current="true" style="background:#2e5078;">
                    Send us your Feedback
                </a>
                {% endif %}

                <button type="button" class="list-group-item list-group-item-action">
                    {{customer.testimony.comment}}
                </button>

            </div>
        </div>
    </div>
</div>
<hr style="width: 70%;"/><br/>
{% endif %}

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<br><br><br>
<div class="container tm-container-contact">
    <div class="row">
        <div class="text-center col-12">
            <h2 class="tm-section-title mb-2">Register as Customer</h2>
            <p class="mb-4">
                Fill out the form and submit
            </p>
        </div>

        <div class="col-sm-12 col-md-6">
            <center><div id="used-username" style="font-size:13px;">Checker</div></center>
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form|crispy }}
             <input type="submit" class="btn tm-btn-submit" value="Submit">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/testimony.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Testimony{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<br><br><br>
<div class="container tm-container-contact">
    <div class="row">
        <div class="col">
              <center><h2 class="tm-section-title mb-4">Write your testimony</h2></center>
        </div>
    </div><br>
    <div class="row">
        <div class="text-center col-7 mr-auto">
            <h4 class="mb-4">
                Fill out the form and submit
            </h4>
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form|crispy }}
             <input type="submit" class="btn tm-btn-submit" value="Submit">
            </form>
        </div>

        <div class="col-3 ml-auto">
            <h4 class="mb-4">Write your impressions</h4>
            <p>Leave your impressions, suggestions and critics. After admin validation, it will be
            posted on our landing page.</p>
        </div>
        <div class="col-sm-12 col-md-6">

        </div>
    </div>
</div>

{% endblock content %}